### ISSUE TITLE
Score Submission despite activated longer Saber

### ISSUE THREAD

**Issue by GregiPlays** [Shadnix-was-taken/BeatSaber-SaberTailor#21]
The last days i experimented more with SaberTailor and found the Option for longer Saber. But most told me that the score submission will be deactivated for this. 

However, after a test I found out that this is not the case for me and I still submit my scores to scoresaber when I play. Is this normal?

**Comment by Shadnix-was-taken** [comment]
The length options are divided into two main options:
* Changing saber length without scaling the hitbox
* Changing saber length with scaling the hitbox

The first part is a cosmetic only option which doesn't change the gameplay at all. That is also the default, if you activate length scaling. In that case, the expected outcome is for score submission to work as normal.

Only if you activate the extra option "scale hitbox" in the menu, then score submission will be disabled, as at this point, the scaling actually changes gameplay.

My last test was done with Beat Saber 1.8.0 release, so there might be an issue. Can you please double check your options and confirm or deny, if you this described expected behavior or not?

**Comment by Shadnix-was-taken** [comment]
So far, I haven't been able to reproduce an issue here and I've also gotten zero other reports. 
Seeing as this issue has also seen no additional replies, I'll close this issue.
